# Generated by Django 4.2.6 on 2024-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("event_name", models.CharField(max_length=200)),
                ("event_note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
