# Generated by Django 4.2.6 on 2025-01-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("〇", "出席"), ("△", "遅刻"), ("×", "欠席")],
                default="×",
                max_length=2,
            ),
        ),
    ]
