# Generated by Django 4.2.6 on 2025-01-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_student_password_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("〇", "出席"), ("×", "欠席"), ("△", "遅刻")],
                default="×",
                max_length=1,
            ),
        ),
    ]
