# Generated by Django 4.2.6 on 2025-01-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_student_registration_date_student_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="registration_date",
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
